services:

  usm_peleng:
    build:
      context: ${USERSIDE_BASE_DIR}/usm_peleng
    environments:
      USERSIDE_API_KEY: 'api-secret-key'
      # DELAY_BEFORE: 0
      # CITIES_LIST: ''
      # IS_ARP_POLLING: 0
    volumes:
      - ${USERSIDE_BASE_DIR}/usm_peleng/module:/app
      - ${USERSIDE_BASE_DIR}/usm_peleng/log:/var/log/usm_peleng
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal